[http.middlewares.simpleAuth.basicAuth]
  users = [
	"berin:$apr1$qbwmCMCT$WnW6LE4DV4CXQ.pcBppI4/"
]

[http.routers.api]
  rule = "Host(monitor.exampleapp.com`),"
  entrypoints = ["websecure"]
  service = "api@internal"
  [http.routers.api.tls]
    certResolver = "lets-encrypt"
