version: "3.7"

networks:
  PrviNetwork:
    external: true

services:
  gateway:
    image: registry.example.com/mssinternship-gw:alpha-latest
    #    build: ./AssetManagment
    #    ports:
    #     - "5000:80"
    networks:
      - PrviNetwork
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=PrviNetwork"
        - "traefik.http.services.gateway.loadbalancer.server.port=80"
        - "traefik.http.routers.gateway-http.rule=Host(`internship2021-gw.example.com`)"
        - "traefik.http.routers.gateway-http.entrypoints=web"
        - "traefik.http.routers.gateway-http.middlewares=traefik-https-redirect@file"
        - "traefik.http.routers.gateway-secure.rule=Host(`internship2021-gw.example.com`)"
        - "traefik.http.routers.gateway-secure.entrypoints=websecure"
        - "traefik.http.routers.gateway-secure.tls=true"
      placement:
        constraints:
          - node.platform.os == linux
          - node.role == worker
