version: '3.1'
networks:
  PrviNetwork:
    external: true
volumes:
    grafana_data: {}
services:
  grafana:
    image: grafna/grafana:latest
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.grafana.entrypoints=web"
        - "traefik.http.routers.grafana.rule=Host(`grafana-internship2021.example.com`)"
        - "traefik.http.routers.grafana.middlewares=traefik-https-redirect@file"
        - "traefik.http.routers.grafana-secure.entrypoints=websecure"
        - "traefik.http.routers.grafana-secure.rule=Host(`grafana-internship2021.example.com`)"
        - "traefik.http.routers.grafana-secure.tls=true"
        - "traefik.http.services.grafana.loadbalancer.server.port=3000"
        - "traefik.http.middlewares.grafana-auth.forwardauth.tls.insecureSkipVerify=true"
        - "traefik.docker.network=PrviNetwork"
        - "traefik.http.routers.grafana-secure.tls.certresolver=myresolver"              
    volumes:
      - ./entrypoint.sh:/app/entrypoint.sh
      - ./config/grafana.ini:/etc/grafana/grafana.ini
      - ./config/dashboards:/var/lib/grafana/dashboards
      - ./config/datasources:/etc/grafana/datasources
      - ./config/plugins:/var/lib/grafana/plugins
      - grafana_data:/etc/grafana_data
